spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=1000
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
springdoc:
  swagger-ui:
    path: /swagger-ui.html